version: "3.7"

networks:
    projetoString-net:
    name: projetoString-net
    driver: bridge
   

services:

  config-server:
    image: projetoString/config-server:latest
    container_name: "projetoString-config-server"
    networks:
      - projetoString-net
    ports:
      - 8888:8888

  discovery-service:
    image: projetoString/dicovery-server:latest
    container_name: "projetoString-discovery-server"
    environment:
      SPRING_CLOUD_CONFIG_URI: http://config-server:8888
    networks:
      - projetoString-net
    ports:
      - 9091:9091
    depends_on:
      - config-server

    projetoString-mongo-database:
    image: mongo:latest
    container_name: "projetoString-vendas-database"
    networks:
      - projetoString-net
    ports:
      - 28017:27017

  cliente-service:
    image: projetoString/cliente-service:latest
    container_name: "projetoString-cliente-service"
    environment:
      PORT: "8080"
      SPRING_CLOUD_CONFIG_URI: http://config-server:8888
      MONGODB_URL: projetoString-mongo-database
      DISCOVERY_HOST: discovery-service
    networks:
      - projetoString-net
    ports:
      - 8081:8080
    depends_on:
      - config-server
      - discovery-service
      - projetoString-mongo-database

    fornecedor-service:
        image: projetoString/fornecedor-service:latest
        container_name: "projetoString-fornecedor-service"
        environment:
          PORT: "8080"
          SPRING_CLOUD_CONFIG_URI: http://config-server:8888
          MONGODB_URL: projetoString-mongo-database
          DISCOVERY_HOST: discovery-service
        networks:
          - projetoString-net
        ports:
          - 8085:8080
        depends_on:
          - config-server
          - discovery-service
          - projetoString-mongo-database

  produto-service:
    image: projetoString/produto-service:latest
    container_name: "projetoString-produto-service"
    environment:
      PORT: "8080"
      SPRING_CLOUD_CONFIG_URI: http://config-server:8888
      MONGODB_URL: projetoString-mongo-database
      DISCOVERY_HOST: discovery-service
    networks:
      - projetoString-net
    ports:
      - 8082:8080
    depends_on:
      - config-server
      - discovery-service
      - projetoString-mongo-database
  
  venda-service:
    image: projetoString/venda-service:latest
    container_name: "projetoString-venda-service"
    environment:
      PORT: "8080"
      SPRING_CLOUD_CONFIG_URI: http://config-server:8888
      MONGODB_URL: projetoString-mongo-database
      DISCOVERY_HOST: discovery-service
    networks:
      - projetoString-net
    ports:
      - 8083:8080
    depends_on:
      - config-server
      - discovery-service
      - projetoString-mongo-database

    compra-service:
        image: projetoString/compra-service:latest
        container_name: "projetoString-compra-service"
        environment:
          PORT: "8080"
          SPRING_CLOUD_CONFIG_URI: http://config-server:8888
          MONGODB_URL: projetoString-mongo-database
          DISCOVERY_HOST: discovery-service
        networks:
          - projetoString-net
        ports:
          - 8084:8080
        depends_on:
          - config-server
          - discovery-service
          - projetoString-mongo-database